# Change these first
owner: magmahost # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  links:
    - rel: stylesheet
      href: https://magmahost.net/assets/bootstrap/css/bootstrap.min.css
    - rel: stylesheet
      href: https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap
    - rel: stylesheet
      href: https://magmahost.net/assets/css/styles.min.css
  css: "body { font-family: 'Inter', sans-serif !important } nav[class^='svelte'], nav[class*=' svelte']{ display: none !important }"
  customHeadHtml: "<nav class='navbar navbar-light navbar-expand-lg navigation-clean'><div class='container'><a class='navbar-brand' href='https://magmahost.net/'><img src='https://magmahost.net/assets/img/magmahost-logo.svg' style='width:74px'></a><button data-bs-toggle='collapse' class='navbar-toggler' data-bs-target='#navcol-1' id='menuToggle'><span class='visually-hidden'>Toggle navigation</span><svg xmlns='http://www.w3.org/2000/svg' width='1em' height='1em' viewBox='0 0 24 24' fill='none'><path d='M4 6H20M4 12H20M4 18H20' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'></path></svg></button><div class='collapse navbar-collapse' id='navcol-1'><ul class='navbar-nav ms-auto'><li class='nav-item'><a class='nav-link active' href='https://magmahost.net/cpanel-web-hosting'>cPanel Web Hosting</a></li><li class='nav-item'><a class='nav-link' href='https://magmahost.net/discord-server'>Discord</a></li><li class='nav-item'><a class='nav-link' href='https://magmahost.net/magmapanel'>MagmaPanel</a></li><li class='nav-item'><a class='btn btn-primary d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex d-xxl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center justify-content-xl-center align-items-xl-center justify-content-xxl-center align-items-xxl-center' role='button' href='https://billing.magmahost.net/'><svg xmlns='http://www.w3.org/2000/svg' width='1em' height='1em' viewBox='0 0 20 20' fill='none' style='width:24px;height:24px;margin-right:9px'><path fill-rule='evenodd' clip-rule='evenodd' d='M10 9C11.6569 9 13 7.65685 13 6C13 4.34315 11.6569 3 10 3C8.34315 3 7 4.34315 7 6C7 7.65685 8.34315 9 10 9ZM3 18C3 14.134 6.13401 11 10 11C13.866 11 17 14.134 17 18H3Z' fill='currentColor'></path></svg>Client Area</a></li></ul></div></div></nav>"
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
